CLASS zz1_cl_indep_req DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZZ1_I_INDEP_REQ.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZ1_CL_INDEP_REQ IMPLEMENTATION.
ENDCLASS.
